Repository polycube-network/polycube, pull requests merged in 2019-06, with the labels that each got.

#137 pcn-nat: fix natting-tables show
  src/services/pcn-nat/src/Nat_dp_common.c
  src/services/pcn-nat/src/NattingTable.h
Labels: hold

#145 Documentation: update list of dependencies
  Documentation/installation.rst
  scripts/install.sh
Labels: documentation

#148 polycubed: fix packet out deadlock when attaching transparent cubes
  src/polycubed/src/port.cpp
  src/polycubed/src/port.h
Labels: bug, component/libpolycube

#144 pcn-iptables: update and unify documentation
  Documentation/components/iptables/pcn-iptables.rst
  src/components/iptables/README.md
Labels: hold

#147 pcn-firewall: implement datapath optimizations
  src/services/pcn-firewall/src/CMakeLists.txt
  src/services/pcn-firewall/src/Chain.cpp
  src/services/pcn-firewall/src/Chain.h
  src/services/pcn-firewall/src/ChainStats.cpp
  src/services/pcn-firewall/src/Firewall.cpp
  src/services/pcn-firewall/src/Firewall.h
  src/services/pcn-firewall/src/SessionTable.cpp
  src/services/pcn-firewall/src/SessionTable.h
  src/services/pcn-firewall/src/Utils.cpp
  src/services/pcn-firewall/src/datapaths/Firewall_ChainForwarder_dp.c
  src/services/pcn-firewall/src/datapaths/Firewall_ConntrackLabel_dp.c
  src/services/pcn-firewall/src/datapaths/Firewall_ConntrackMatch_dp.c
  src/services/pcn-firewall/src/datapaths/Firewall_ConntrackTableUpdate_dp.c
  src/services/pcn-firewall/src/datapaths/Firewall_Horus_dp.c
  src/services/pcn-firewall/src/datapaths/Firewall_IpLookup_dp.c
  src/services/pcn-firewall/src/datapaths/Firewall_L4PortLookup_dp.c
  src/services/pcn-firewall/src/datapaths/Firewall_L4ProtocolLookup_dp.c
  src/services/pcn-firewall/src/datapaths/Firewall_Parser_dp.c
  src/services/pcn-firewall/src/datapaths/Firewall_TcpFlagsLookup_dp.c
  src/services/pcn-firewall/src/defines.h
  src/services/pcn-firewall/src/modules/ActionLookup.cpp
  src/services/pcn-firewall/src/modules/BitScan.cpp
  src/services/pcn-firewall/src/modules/ChainForwarder.cpp
  src/services/pcn-firewall/src/modules/ConntrackLabel.cpp
  src/services/pcn-firewall/src/modules/ConntrackMatch.cpp
  src/services/pcn-firewall/src/modules/ConntrackTableUpdate.cpp
  src/services/pcn-firewall/src/modules/DefaultAction.cpp
  src/services/pcn-firewall/src/modules/Horus.cpp
  src/services/pcn-firewall/src/modules/IpLookup.cpp
  src/services/pcn-firewall/src/modules/L4PortLookup.cpp
  src/services/pcn-firewall/src/modules/L4ProtocolLookup.cpp
  src/services/pcn-firewall/src/modules/Parser.cpp
  src/services/pcn-firewall/src/modules/Program.cpp
  src/services/pcn-firewall/src/modules/TcpFlagsLookup.cpp
Labels: enhancement, service/pcn-firewall

#140 Add Shadow Services
  Documentation/cubes.rst
  Documentation/developers/controlplane.rst
  Documentation/developers/datapath.rst
  src/libs/polycube/include/polycube/services/cube.h
  src/libs/polycube/include/polycube/services/cube_iface.h
  src/libs/polycube/include/polycube/services/port.h
  src/libs/polycube/include/polycube/services/port_iface.h
  src/libs/polycube/include/polycube/services/utils.h
  src/libs/polycube/src/port.cpp
  src/libs/polycube/src/utils.cpp
  src/polycubed/src/base_model.cpp
  src/polycubed/src/base_model.h
  src/polycubed/src/cube.cpp
  src/polycubed/src/cube.h
  src/polycubed/src/cube_factory_impl.cpp
  src/polycubed/src/cube_factory_impl.h
  src/polycubed/src/cube_tc.cpp
  src/polycubed/src/cube_tc.h
  src/polycubed/src/cube_xdp.cpp
  src/polycubed/src/cube_xdp.h
  src/polycubed/src/port.cpp
  src/polycubed/src/port.h
  src/polycubed/src/server/Resources/Data/BaseModel/ConcreteFactory.cpp
  src/polycubed/src/utils/netlink.cpp
  src/polycubed/src/utils/netlink.h
  src/polycubed/src/utils/ns.cpp
  src/polycubed/src/utils/ns.h
  src/polycubed/src/utils/veth.cpp
  src/polycubed/src/utils/veth.h
  src/services/datamodel-common/polycube-standard-base.yang
  src/services/pcn-router/src/CMakeLists.txt
  src/services/pcn-router/src/Ports.cpp
  src/services/pcn-router/src/Ports.h
  src/services/pcn-router/src/Router.cpp
  src/services/pcn-router/src/Router.h
  src/services/pcn-router/src/Router_dp.c
  src/services/pcn-router/test/test_shadow/test1.sh
  src/services/pcn-router/test/test_shadow/test2.sh
  src/services/pcn-router/test/test_shadow/test3.sh
  src/services/pcn-router/test/test_shadow/test4.sh
Labels: under-review

#141 load old topology at startup and save each modification to file
  Documentation/polycubed/polycubed.rst
  src/libs/polycube/include/polycube/services/cube.h
  src/polycubed/src/CMakeLists.txt
  src/polycubed/src/base_model.cpp
  src/polycubed/src/base_model.h
  src/polycubed/src/config.cpp
  src/polycubed/src/config.h
  src/polycubed/src/cubes_dump.cpp
  src/polycubed/src/cubes_dump.h
  src/polycubed/src/peer_iface.cpp
  src/polycubed/src/peer_iface.h
  src/polycubed/src/polycubed.cpp
  src/polycubed/src/polycubed_core.cpp
  src/polycubed/src/polycubed_core.h
  src/polycubed/src/port.cpp
  src/polycubed/src/rest_server.cpp
  src/polycubed/src/rest_server.h
  src/polycubed/src/server/Parser/YangNodes.tcpp
  src/polycubed/src/server/Resources/Body/ListKey.h
  src/polycubed/src/server/Resources/Data/BaseModel/CMakeLists.txt
  src/polycubed/src/server/Resources/Data/BaseModel/ConcreteFactory.cpp
  src/polycubed/src/server/Resources/Data/BaseModel/LeafListResource.cpp
  src/polycubed/src/server/Resources/Data/BaseModel/LeafListResource.h
  src/polycubed/src/server/Resources/Endpoint/LeafListResource.cpp
  src/polycubed/src/server/Resources/Endpoint/LeafListResource.h
  src/polycubed/src/server/Resources/Endpoint/LeafResource.cpp
  src/polycubed/src/server/Resources/Endpoint/ListResource.cpp
  src/polycubed/src/server/Resources/Endpoint/ParentResource.cpp
  src/polycubed/src/server/Resources/Endpoint/Resource.cpp
  src/polycubed/src/server/Resources/Endpoint/Resource.h
  src/polycubed/src/server/Resources/Endpoint/Service.cpp
  src/polycubed/src/utils/utils.cpp
  src/polycubed/src/utils/utils.h
  src/services/datamodel-common/polycube-standard-base.yang
  src/services/pcn-nat/src/Nat.cpp
  src/services/pcn-nat/src/Rule.cpp
  src/services/pcn-nat/src/RuleMasquerade.cpp
  src/services/pcn-nat/src/RuleMasquerade.h
  src/services/pcn-router/src/Router.cpp
  src/services/pcn-simplebridge/src/Simplebridge.cpp
Labels: under-review

#156 Vagrant: fix bad url and file name
  tests/vagrant/pcn-k8s/Vagrantfile
Labels: component/k8s

#160 Revert polycubed persistency support
  Documentation/polycubed/polycubed.rst
  src/polycubed/src/CMakeLists.txt
  src/polycubed/src/config.cpp
  src/polycubed/src/config.h
  src/polycubed/src/cubes_dump.cpp
  src/polycubed/src/cubes_dump.h
  src/polycubed/src/peer_iface.cpp
  src/polycubed/src/peer_iface.h
  src/polycubed/src/polycubed.cpp
  src/polycubed/src/polycubed_core.cpp
  src/polycubed/src/polycubed_core.h
  src/polycubed/src/rest_server.cpp
  src/polycubed/src/rest_server.h
  src/polycubed/src/server/Resources/Body/ListKey.h
  src/polycubed/src/server/Resources/Endpoint/LeafResource.cpp
  src/polycubed/src/server/Resources/Endpoint/ListResource.cpp
  src/polycubed/src/server/Resources/Endpoint/ParentResource.cpp
  src/polycubed/src/server/Resources/Endpoint/Resource.cpp
  src/polycubed/src/server/Resources/Endpoint/Resource.h
  src/polycubed/src/server/Resources/Endpoint/Service.cpp
Labels: bug, component/polycubed, hold, priority/urgent, revert

#163 pcn-iptables: fix wrong const type
  src/services/pcn-firewall/src/defines.h
  src/services/pcn-iptables/src/defines.h
Labels: under-review
