Repository polycube-network/polycube, pull requests merged in 2019-03, with the labels that each got.

#76 pcn-firewall: fix id initialize for default rule
  src/services/pcn-firewall/src/ChainRule.cpp
Labels: under-review

#78 libpolycube: remove dead code in cube
  src/libs/polycube/include/polycube/services/base_cube.h
  src/libs/polycube/src/base_cube.cpp
  src/libs/polycube/src/transparent_cube.cpp
Labels: component/libpolycube

#74 Documentation: improve cubes section
  Documentation/cubes.rst
Labels: documentation

#79 PCN-K8S vagrant setup and documentation update
  Documentation/components/k8s/pcn-kubernetes.rst
  tests/vagrant/.gitignore
  tests/vagrant/README.md
  tests/vagrant/pcn-k8s/README.md
  tests/vagrant/pcn-k8s/Vagrantfile
Labels: automation, under-review

#83 Correction to the Vagrantfile href
  Documentation/components/k8s/pcn-kubernetes.rst
Labels: documentation
